# Orchestrator configuration
server:
  port: 8080
  grpc_port: 9090
  host: "0.0.0.0"

etcd:
  endpoints:
    - "localhost:2379"
  prefix: "orchestrator"
  timeout: 5s

scheduler:
  algorithm: "binpacking" # Options: roundrobin, binpacking, spread
  reconciliation_interval: "5s"
  task_timeout: "1h"
  node_timeout: "30s"

logging:
  level: "info" # Options: debug, info, warn, error
  format: "text" # Options: text, json

worker:
  heartbeat_interval: "10s"
  max_retries: 3
  retry_delay: "2s"

resources:
  default_cpu: 1000    # 1 CPU core in millicores
  default_memory: 512  # 512MB
  max_cpu: 4000        # 4 CPU cores
  max_memory: 8192     # 8GB