version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: orchestrator-etcd
    environment:
      - ETCDCTL_API=3
    command: >
      etcd
      --name etcd0
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://etcd:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://etcd:2380
      --initial-cluster etcd0=http://etcd:2380
      --initial-cluster-token my-cluster
      --initial-cluster-state new
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd_data:/etcd-data
    networks:
      - orchestrator-network

  master:
    build:
      context: .
      dockerfile: Dockerfile.master
    container_name: orchestrator-master
    environment:
      - ETCD_ENDPOINTS=etcd:2379
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - etcd
    networks:
      - orchestrator-network

  worker1:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: orchestrator-worker1
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - NODE_IP=worker1
    depends_on:
      - etcd
      - master
    networks:
      - orchestrator-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  worker2:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: orchestrator-worker2
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - NODE_IP=worker2
    depends_on:
      - etcd
      - master
    networks:
      - orchestrator-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  etcd_data:

networks:
  orchestrator-network:
    driver: bridge